<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_918.99_cart-quantity-input</name>
   <tag></tag>
   <elementGuidId>28afd5b4-31e9-49ce-b487-f9ec104dd922</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.cart-quantity-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8615c5a6-bfd6-4be9-87c6-01aff11dfe00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-quantity-input</value>
      <webElementGuid>d6eeb5ba-79a6-4519-92f9-ec079b64b106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c0100ca7-d410-43f3-91e8-2ff30662c124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>481219d0-fab1-4097-8217-09f60cb11c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prooood&quot;)/section[@class=&quot;container content-section&quot;]/div[@class=&quot;cart-items&quot;]/div[@class=&quot;cart-row&quot;]/div[@class=&quot;cart-quantity cart-column&quot;]/input[@class=&quot;cart-quantity-input&quot;]</value>
      <webElementGuid>52096363-e8c7-4367-bbca-883a6f3dac66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='1']</value>
      <webElementGuid>2b4d958d-93be-40ee-b64f-a6e4fe98965f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prooood']/section/div[2]/div/div[2]/input</value>
      <webElementGuid>2d757646-0e1d-433a-a9cb-adb9ed70b735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>7659c186-1459-4d6f-8661-11beb52a1108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>0855ed5e-7899-47f8-b5b4-daff0c522eeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
